#!/bin/bash

set -e -o pipefail

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"

to_install=$(comm -23 <(sort "$DIR/state/pkglist.txt" "$DIR/state/aurlist.txt") <(yay -Qq | sort))
to_remove=$(comm -23 <(pacman -Qq | sort) <(sort "$DIR/state/pkglist.txt" "$DIR/state/aurlist.txt"))

for pkg in $to_install; do
  yay --noconfirm --needed -S "$pkg"
done

for pkg in $to_remove; do
  yay --noconfirm -Rsu "$pkg"
done

sudo cp -rf "$DIR"/state/fslayer/* /

while read -r srvc; do
  sudo systemctl enable "$srvc"
done < "$DIR/state/srvclist.txt"

